// Verifies the C++ AES-256-GCM codec decrypts an enc:v1: payload produced by the .NET AesGcm used in
// secret/Protect-Env.ps1 (the fixture below was generated by that same primitive with a THROWAWAY test
// key — never the production master key). Registered with CTest; runs inside the Docker build.
#include <cassert>
#include <cstdlib>
#include <iostream>
#include <string>

#include "secret_codec.hpp"

using namespace cproxy;

namespace {

// Throwaway test key + a fixture encrypted under it (see the PR notes for how it was generated).
constexpr const char* TEST_KEY_HEX =
    "000102030405060708090a0b0c0d0e0f101112131415161718191a1b1c1d1e1f";
constexpr const char* NAME = "SAMPLE_SECRET";
constexpr const char* PLAINTEXT = "hello-cproxy-42";
constexpr const char* ENC = "enc:v1:yRgkVhMibXS8XKBy-n2BXbqpy0bQiRyoAkZmmS1adE8ibDr1_PRyBsbVGQ";

void marker_detection() {
    assert(is_encrypted(ENC));
    assert(!is_encrypted("plain"));
    assert(!is_encrypted(""));
}

void plaintext_passes_through() {
    assert(decrypt_if_needed("ANY", "just-a-value") == "just-a-value");
}

void decrypts_dotnet_payload() {
    assert(decrypt_if_needed(NAME, ENC) == PLAINTEXT);
}

void wrong_variable_name_fails_the_aad_check() {
    bool threw = false;
    try {
        decrypt_if_needed("DIFFERENT_NAME", ENC);  // same key, wrong AAD -> GCM tag mismatch
    } catch (const std::exception&) {
        threw = true;
    }
    assert(threw);
}

}  // namespace

int main() {
    // Force the codec to use the throwaway test key (env var, not the file path).
    unsetenv("FF_MASTER_KEY_FILE");
    setenv("FF_MASTER_KEY", TEST_KEY_HEX, 1);

    marker_detection();
    plaintext_passes_through();
    decrypts_dotnet_payload();
    wrong_variable_name_fails_the_aad_check();
    std::cout << "secret_codec_test: all assertions passed\n";
    return 0;
}
